spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/proxy-collector
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
integration:
  open-proxy-space:
    url: 'https://openproxy.space'
    delay: 60000
    connectTimeout: 20000
    readTimeout: 20000
  proxy-scrape:
    url: 'https://api.proxyscrape.com/v2'
    delay: 1800000
    connectTimeout: 60000
    readTimeout: 20000
    http:
      path: '/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all'
      enabled: true
    socks4:
      path: '/?request=getproxies&protocol=socks4&timeout=10000&country=all'
      enabled: true
    socks5:
      path: '/?request=getproxies&protocol=socks5&timeout=10000&country=all'
      enabled: true
  proxy-scan:
    url: "https://www.proxyscan.io"
    delay: 60000
    connectTimeout: 60000
    readTimeout: 60000
    http:
      path: '/download?type=http'
      enabled: false
    https:
      path: '/download?type=https'
      enabled: false
    socks4:
      path: '/download?type=socks4'
      enabled: false
    socks5:
      path: '/download?type=socks5'
      enabled: false
  the-speed-x:
    url: 'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master'
    delay: 1800000
    connectTimeout: 20000
    readTimeout: 20000
    http:
      path: '/http.txt'
      enabled: true
    socks4:
      path: '/socks4.txt'
      enabled: true
    socks5:
      path: '/socks5.txt'
      enabled: true
  premium-proxy:
    url: 'https://premiumproxy.net'
#    url: 'https://spys.one'
    delay: 60000
    connectTimeout: 20000
    readTimeout: 20000
    http:
      path: '/full-proxy-list'
#      path: '/en/socks-proxy-list/'
      enabled: false
