integration:
  open-proxy-space:
    url: 'https://openproxy.space'
    delay: 60000
  proxy-scrape:
    url: 'https://api.proxyscrape.com/v2'
    delay: 60000
    http:
      path: '/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all'
      enabled: true
    socks4:
      path: '/?request=getproxies&protocol=socks4&timeout=10000&country=all'
      enabled: true
    socks5:
      path: '/?request=getproxies&protocol=socks5&timeout=10000&country=all'
      enabled: true
  proxy-scan:
    url: "https://www.proxyscan.io"
    delay: 60000
    http:
      path: '/download?type=http'
      enabled: true
    https:
      path: '/download?type=https'
      enabled: true
    socks4:
      path: '/download?type=socks4'
      enabled: true
    socks5:
      path: '/download?type=socks5'
      enabled: true
  the-speed-x:
    url: 'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master'
    delay: 60000
    http:
      path: '/http.txt'
      enabled: true
    socks4:
      path: '/socks4.txt'
      enabled: true
    socks5:
      path: '/socks5.txt'
      enabled: true
